pub mod ai_router;
pub mod aia_orchestrator;
pub mod auth;
pub mod brain_audit;
pub mod brain_controller;
pub mod brain_evaluator;
pub mod brain_policy;
pub mod context_compression;
pub mod decision_algorithm;
pub mod distributed;
pub mod embeddings;
pub mod graph_rag;
pub mod guardrails;
pub mod hybrid_rag;
pub mod iman_journey;
pub mod ingestion_producer;
pub mod islamic_knowledge;
pub mod knowledge_graph_service;
pub mod llm_gateway;
pub mod mcp_registry;
pub mod memory_engine;
pub mod multimodal;
pub mod offline_islamic_corpus;
pub mod outbox_relay;
pub mod phase2;
pub mod pii_redaction;
pub mod qdrant_client;
pub mod semantic_cache;
pub mod semantic_router;
pub mod tafsir_ingestion;
pub mod fatwa_verifier;

pub use ai_router::AiRouter;
pub use aia_orchestrator::AiaOrchestrator;
pub use auth::authenticated_user_id;
pub use auth::ensure_user_scope;
pub use brain_audit::BrainAuditLog;
pub use brain_controller::{BrainController, BrainExecutionPermit};
pub use brain_evaluator::BrainResponseEvaluator;
pub use brain_policy::{BrainPolicyDecision, BrainSafetyPolicy};
pub use context_compression::{
    CompressedEvidenceChunk, CompressionReport, ContextCompressionService,
};
pub use decision_algorithm::decide as decide_request;
pub use decision_algorithm::DefaultModuleClassifier;
pub use decision_algorithm::DefaultSafetyClassifier;
pub use decision_algorithm::EmptyRetriever;
pub use decision_algorithm::StrictFormatter;
pub use embeddings::EmbeddingsService;
pub use graph_rag::{GraphRagResult, GraphRagService};
pub use guardrails::Guardrails;
pub use hybrid_rag::{HybridRagResult, HybridRagService, HybridRetrievedChunk};
pub use iman_journey::ImanJourneyService;
pub use ingestion_producer::IngestionProducer;
pub use islamic_knowledge::AskIslamicRequest;
pub use islamic_knowledge::IslamicAnswerService;
pub use islamic_knowledge::IslamicKnowledgeRepository;
pub use islamic_knowledge::QdrantCollectionPlan;
pub use knowledge_graph_service::{
    KnowledgeGraphEntityView, KnowledgeGraphLookupResult, KnowledgeGraphService,
};
pub use llm_gateway::{SakinaLlmGateway, SakinaLlmGatewayRequest, SakinaLlmGatewayResult};
pub use mcp_registry::{McpConnectorRegistry, McpConnectorSpec};
pub use memory_engine::{MemoryEngine, MemoryEntry, MemoryWriteOutcome, MemoryWriteRequest};
pub use multimodal::{MultimodalAnalysisRequest, MultimodalAnalysisResult, MultimodalService};
pub use offline_islamic_corpus::fallback as offline_fallback;
pub use offline_islamic_corpus::lookup as offline_lookup;
pub use outbox_relay::OutboxRelay;
pub use phase2::Phase2Repository;
pub use qdrant_client::QdrantVectorDB;
pub use semantic_cache::{SemanticCacheEntry, SemanticCacheService, SemanticCacheStats};
pub use semantic_router::SemanticRouter;
