apiVersion: v1
kind: Service
metadata:
  name: sakina-frontend
  namespace: sakina-prod
  labels:
    app: sakina-frontend
spec:
  type: ClusterIP
  selector:
    app: sakina-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakina-frontend
  namespace: sakina-prod
  labels:
    app: sakina-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sakina-frontend
  template:
    metadata:
      labels:
        app: sakina-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
        - name: frontend
          image: ghcr.io/serverax/sakina-frontend:2eb50fe
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
